# This is a basic workflow to help you get started with Actions
name: pa11y tests
#  Will run on 6pm every weekday
on:
  schedule:
    - cron: "0 18 * * 1-5"

jobs:
  pally-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

#Checks out the code from the repository.
    steps:
      - uses: actions/checkout@v3
#Sets up the Node.js environment.
      - name: use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
#Installs the dependencies required for running the tests.
      - name: install pa11y-ci dependencies
        run: npm install
      - run: npm run build --if-present
      - name: pa11y testing
#Runs the test-pa11y script and prints the results.
        env:
          PA11Y_TEST: ${{ vars.Pa11y-ci }}
        uses: npm run pa11y-ci

