# This is a basic workflow to help you get started with Actions
name: pa11y-ci
#  Will run on 6pm every weekday
on:
  schedule:
    - cron: "0 18 * * 1-5"
      
  pull_request:
    branches: [ "main" ]

jobs:
  pally-ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]

    #Checks out the code from the repository.
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      #Sets up the Node.js environment.
      - name: use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      #Installs the dependencies required for running the tests.
      - name: install pa11y-ci dependencies
        run: npm install --save-dev pa11y-ci
      #runs pa11y & prints results
      - name: run pa11y-ci and print results
        run: npm run test-pa11y

#jobs:
#  pa11y:
#    name: Pa11y tests
#    runs-on: ubuntu-latest
#
#    strategy:
#      matrix:
#        node-version: [14.x]
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Use Node.js ${{ matrix.node-version }}
#        uses: actions/setup-node@v3
#        with:
#          node-version: ${{ matrix.node-version }}
#          cache: 'npm'
#
#      - name: Install pa11y-ci dependencies
#        run: npm install
#
#      - name: Start application
#        run: npm start > /dev/null 2>&1 &
#
#      - name: Wait for application to start
#        run: sleep 10
#
#      - name: Run pa11y-ci tests
#        run: npm run test-pa11y



